#!/bin/bash

CC=gcc
CFLAGS="-Wall -pedantic -ggdb --std=gnu99"

$CC $CFLAGS -c page.c

for i in *.c; do
	if [ "$i" != "page.c" ]; then
		echo $CC $CFLAGS -c $i
		$CC $CFLAGS -c $i
		echo $CC $CFLAGS $(echo $i | sed -e 's/.c$/.o/') page.o -o $(echo $i | sed -e 's/.c$/.bin/')
		$CC $CFLAGS $(echo $i | sed -e 's/.c$/.o/') page.o -o $(echo $i | sed -e 's/.c$/.bin/')
	fi
done
