#!/bin/bash

CC=gcc
CFLAGS="-Wall -pedantic -O3 -ggdb --std=gnu99"

for i in *.c; do
	echo $CC $CFLAGS -o $(echo $i | sed -e 's/\.c$/\.bin/') $i
	$CC $CFLAGS -o $(echo $i | sed -e 's/\.c$/\.bin/') $i
done
